### ISSUE TITLE
Service automatic resubscription

### ISSUE THREAD

**Issue by 256dpi** [256dpi/gomqtt#5]
It should be possible to configure the service to automatically resubscribe to topics if required.

**Comment by ludanfeng** [comment]
Just use a map[string]packet.Subcription to record all subscriptions, topic as key. If topics are the same, new one will replace the old one.

[overlap]
When Clients make subscriptions with Topic Filters that include wildcards, it is possible for a Client’s subscriptions to overlap so that a published message might match multiple filters. In this case the Server MUST deliver the message to the Client respecting the maximum QoS of all the matching subscriptions [MQTT-3.3.5-1]. In addition, the Server MAY deliver further copies of the message, one for each additional matching subscription and respecting the subscription’s QoS in each case.
 
[identical]
If a Server receives a SUBSCRIBE Packet containing a Topic Filter that is identical to an existing Subscription’s Topic Filter then it MUST completely replace that existing Subscription with a new Subscription. The Topic Filter in the new Subscription will be identical to that in the previous Subscription, although its maximum QoS value could be different. Any existing retained messages matching the Topic Filter MUST be re-sent, but the flow of publications MUST NOT be interrupted [MQTT-3.8.4-3].

**Comment by 256dpi** [comment]
Added in release `v0.9.0`.
